[versions]
core-ktx = "1.10.1"
appcompat = "1.6.1"
material = "1.9.0"
lifecycle-runtime-ktx = "2.3.1"
agp = "8.0.2"
kotlin = "1.8.20"
ktor = "2.2.3"

#layouts
constraintlayout = "2.1.4"
coordinatorlayout = "1.2.0"
swiperefreshlayout = "1.2.0-alpha01"

#Compose
compose = "1.4.3"
material3 = "1.1.1"
activity-compose = "1.7.2"
constraintlayout-compose = "1.0.1"
runtime-compose = "2.6.1"

#Navigation
navigation-fragment-ktx = "2.6.0"
navigation-safe-args-gradle-plugin="2.6.0"
#Room
room = "2.5.2"

#lifecycle
lifecycle_extentions = "2.2.0"
lifecycle = "2.6.1"

#coroutines
coroutines = "1.6.4"

#swipe decor
recyclerview-swipedecorator = "1.4"

#gson
gson = "2.10.1"

#retrofit
retrofit = "2.9.0"
logging = "5.0.0-alpha.1"

#lottie
lottie = "6.0.1"
yoyo = "2.4"

#work manager
work_manager = "2.8.1"

#auth sdk
authsdk = "2.5.1"

#dagger
dagger = "2.46.1"

#Junit
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"


[libraries]
core-ktx = {group = "androidx.core", name = "core-ktx", version.ref = "core-ktx"}
appcompat = {group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

lifecycle-extentions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle_extentions" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

#coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }

#Gradle plugins
agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

#Junit
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

#Compose
androidx-compose = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-tooling-compose = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview-compose = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose" }

#Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }


#Room
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }


#Nav save args
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-fragment-ktx" }

#Animations
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
yoyo = { group = "com.daimajia.androidanimations", name = "library", version.ref = "yoyo" }

#YandexAuth
authsdk = { group = "com.yandex.android", name = "authsdk", version.ref = "authsdk" }

#Dagger-2
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-android-compiler = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }

#WorkManager
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work_manager" }

#Layouts
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

swipedecorator = { group = "it.xabaras.android", name = "recyclerview-swipedecorator", version.ref = "recyclerview-swipedecorator" }

#Retrofit
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

#OkHttp
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging" }

#Ktor
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-safe-args-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "agp" }

[bundles]

ktor = ["ktor-okhttp", "ktor-negotiation", "ktor-serialization", "ktor-logging"]

navigation = ["navigation-ui-ktx", "navigation-fragment-ktx"]

compose-core = ["androidx-compose", "androidx-ui-tooling-compose", "androidx-ui-tooling-preview-compose", "androidx-activity-compose", "androidx-lifecycle-viewmodel-compose"]
compose-material = ["compose-material", "compose-material3"]

retrofit = ["retrofit2", "gson-converter", "okhttp-logging"]

room = ["room", "room-runtime"]

dagger = ["dagger-android-support", "dagger-android", "dagger"]
dagger-compiler = ["dagger-android-compiler", "dagger-compiler"]